codegen: Don't add deadcode attribute in generated code
This breaks at least the case of generated code being imported through
`include!` macro:

```
error: an inner attribute is not permitted in this context
 --> /home/zeenix/checkout/dbus-rs/target/debug/build/codegen-tests-34abc2ff2e0eca43/out/policykit.rs:3:3
  |
3 | #![allow(dead_code)]
  |   ^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.
```

This will become a problem in the following patch, where we use `include!`
macro to include the generated code into the tests code.